hash-format = "sha256"

[[files]]
file = "LICENSE"
hash = "002c2696d92b5c8cf956c11072baa58eaf9f6ade995c031ea635c6a1ee342ad1"

[[files]]
file = "config/yosbr/config/crosshairaddons.json"
hash = "b75736290ef479d26ca52d0e4298d803c01b4050dd090a843a1188d688b2504b"

[[files]]
file = "config/yosbr/config/cull-less-leaves.json"
hash = "edbe4c405e6f4d1afc642ac979b3dc4453abfc6834506f7be9627458670e23d7"

[[files]]
file = "config/yosbr/config/customwindowtitle-client.toml"
hash = "cf576f8b89fba245c546db3ef27e28a46c1aae0914d20c75f7e78918c447204d"

[[files]]
file = "config/yosbr/config/early-loading-bar.json"
hash = "e3c47cdb5a68b9ba918cc0c0c2476b7c272c4e148fe81826e52fd68da37f1d79"

[[files]]
file = "config/yosbr/config/emotecraft.json"
hash = "503e9e4c16523f50e40e35784e92e2aab2a026d0422a63dd2739b93ef7f3716c"

[[files]]
file = "config/yosbr/config/figura.json"
hash = "96d93b202c2f6875b93ca6aaf73481e2c6ccd2b5fda29a31f446ca3b6ff238f9"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3da48a1e456c64065654658d6b0bc21b78ecaea0d6f469e4d96d840011fd7f50"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "d2e72b5f7489638cf59c5b10b0be9688e7e6ce0dfe6c3e02d68c2ce41ab0d19d"

[[files]]
file = "config/yosbr/config/notenoughanimations.json"
hash = "ed7dfd2c0db1072caab00c05ed29b4e1d8075d2ce686eaa022a283c397940cbc"

[[files]]
file = "config/yosbr/config/replaymod.json"
hash = "07dbafbbac4ebb2bd0a4de319ea2416f9d443f68229a1b45e595abbf902a943b"

[[files]]
file = "config/yosbr/config/scoreboard-overhaul.json"
hash = "aac4f2225b8dec031d07acb5c2a7dda26b5df8b594db7231bbada81454fdc585"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "2445c054393ab40304c9fde7008b404323cd7302e0411d4b4aa32de5f362701e"

[[files]]
file = "config/yosbr/config/zoomify.json"
hash = "839f3e7347c514b0fb4b02fb86fd263943dea9d7a1e60e70fdb3011abf0a944a"

[[files]]
file = "config/yosbr/options.txt"
hash = "fc20d9b1657156c6f8b9ee8fef49568e04033d8d85ea66385c38f53092f113c9"

[[files]]
file = "config/yosbr/servers.dat"
hash = "2fb0c8230eaa5ce3b7a67df7177d491937dbce366aea65584753b22aca30c8da"

[[files]]
file = "mods/amecs.pw.toml"
hash = "f55c8a607dbd0c8e23b0ae021d2f01cefac1c6373c42bb3e5f457563636ed5f0"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "45d8570e9c13f5265d9d833ba2431e982ab9cf2760e86c6d5fd62dd3c092e18c"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "06d9fc289964f42dfad761ff34dc7c2f09bb7dde3d8fc54954ad01f15c8714ed"
metafile = true

[[files]]
file = "mods/better-clouds.pw.toml"
hash = "8707f0a17d65424f2372a04e45bb1e3292602f915b42500cbb86734077cc59c0"
metafile = true

[[files]]
file = "mods/better-highlighting.pw.toml"
hash = "b9a65005514829b0b24c619bed56f664ce52adbd930903e9c755ec3202d6196b"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "378184d2642a7ed600c63b8a3f93a76255592a0f4695c992a130784f1bb2dc94"
metafile = true

[[files]]
file = "mods/better-suggestions.pw.toml"
hash = "21b767cbde76f273b38669fce5e0dab3c790e8811591c05057c84e064aa502ea"
metafile = true

[[files]]
file = "mods/chatanimation.pw.toml"
hash = "ba0b23cf88c96c480618d0de40b5aa98e070d26a023aad945298b01f8451d0ba"
metafile = true

[[files]]
file = "mods/clean-f3.pw.toml"
hash = "23e0641f74cf1f8590466b3f91517d9a40f5ed4372748191032871123961fb38"
metafile = true

[[files]]
file = "mods/clientsidenoteblocks.pw.toml"
hash = "614da319097ce96717cd56c3ff3313b8204fc13625d0f70bff27b605725a751e"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "ae11fe7c63207b7257ecb782d421655c6f56adb551b78ad430066edc94bee3b1"
metafile = true

[[files]]
file = "mods/collision-fix.pw.toml"
hash = "166ea8ea38edc04491553912a7e12ec7f7704712cdfebc71eb37bddfd5a2fd1b"
metafile = true

[[files]]
file = "mods/colorful-subtitles.pw.toml"
hash = "25e3084354d6f5f3a71438747fd79a0154c2693211f614ce68a852115810003b"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "8459128658c0148ba1b89d87b4c86bd62f236c73cff860090eba0b08e49ae9ce"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "e7513fdc9b93652c928a5af59e9dc6a5b21dfe5200fe78883a6fa56d3cdefa1f"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "50c43b88f972372cdf5229e986ec4433724be6ac5971e54c492f8e573951de16"
metafile = true

[[files]]
file = "mods/crosshair-addons-public.pw.toml"
hash = "8676a3f9975536a6fc2ddcb812138cb1e0ce78e5d2321124f25892d877063c4d"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "df4e3de1d55d3b06b47a18a61d64c6e9fb6a8cf483fa2ff09a46bf5ff40f8cb6"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "ad1ee78be7479032b482ee2c4e5cc5ebb0d5f74dd2a498108a41b6b74bcd1858"
metafile = true

[[files]]
file = "mods/custom-window-title.pw.toml"
hash = "d95e86e4ac6984ded372855f5ed4cca36308f389d8046fde1c37a5315739eecd"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "7abb69378bbeb4e07a6573f5c3ec8c362b1a14c3a70f67a22a57e844547d7cd2"
metafile = true

[[files]]
file = "mods/early-loading-bar.pw.toml"
hash = "667a1607b97bf288b343142ec340d6cfb80e42c975f4b8398ffb719ea6805a4e"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "c9102ad224c1496927d326707ee2cd2a2cfd6f278f05e23a19aa45395306daf6"
metafile = true

[[files]]
file = "mods/effecttimerplus.pw.toml"
hash = "1fd492cd1c570fd7fd953f4bcc27ae204b4107e1d21a54efc9c7d512cc1b5141"
metafile = true

[[files]]
file = "mods/emotecraft.pw.toml"
hash = "e965542bde2548fdedc2ab3b1d9a24705d462e4f3e2c841f527ac4595b1a0d1a"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "58a487d9e3761d18f529cf141c873ea054e8f26c5e90601a3c8cf60fc723b22d"
metafile = true

[[files]]
file = "mods/f3sconfirm.pw.toml"
hash = "edd246bb7ccb7b5cbe21ee578e2a3b276401fcb80d30de78e9c258c42b6bc14f"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "c784cee4a8eed3f2b36172b8c5a119a62a28880d15e7f169947c935bf3bf4bb3"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "94f000249d21c4fc3b7744f9579bb6ac0d48e6bf4860fad16f23c997950a47f3"
metafile = true

[[files]]
file = "mods/fadeless.pw.toml"
hash = "07a47e267bea1fdf72011e12b96521c08a8cf95078d1276b6ca655d0e183e432"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "db5a6f61c331614600c1e6d529c5c1da49fda2959f8030ee195ab3c2c54597f5"
metafile = true

[[files]]
file = "mods/faster-random.pw.toml"
hash = "605fe60f2ada4333e88ec2fa66cb57d0635292d83eee8d1ad40f2485d72ef013"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "86cbfa8adbbb8be527f95aca49b427f892aa780773df141dfd7f4ffd02740bbd"
metafile = true

[[files]]
file = "mods/figura.pw.toml"
hash = "7bd50f9e121e66862fbfb48da10ec96ef5671fe24dd85367830632273c08efc2"
metafile = true

[[files]]
file = "mods/highlight.pw.toml"
hash = "fe8c8940f8496c28c480286e1214f61113aa3f79e065032d136048b9a2a8cda4"
metafile = true

[[files]]
file = "mods/i-see-my-armored-hand.pw.toml"
hash = "1f49b7a70c72b4d40b543a00be287e03dfa035d7d7e86f550c76db219760ca74"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "60adfc1ee75f10a7290e18f3e2b82601a3d3915db0c53dabe08dd17daf1c7d76"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "99efc9e805ce2888680d3cacb9be65733c6d4a8cfcb77e1976205f758db24346"
metafile = true

[[files]]
file = "mods/itemphysic-lite.pw.toml"
hash = "a5c8acced1ba890bf52485e4389e40cb0360adee9cbe30be45d1ad8caaab30cc"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "9063bac3fdf585a43d318e3f9773475a28ecb8fe80bc7689cc480851eef97420"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "8508e46b7e272d79dc6b3cc0149f9fd132c701369bcb2abb5c35da3ed92b27fb"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "39d1aa66bf641027827a4bfcfe2c088ad6506405b0ff603fd65b1a9828d40c94"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ede2f61d6b592f44294fa8790c2f050729c487aa86aba09034f2ef30d45e0e93"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "3a82c08c74d69af0bc30a682da43945005455162276f60efdc3eb5b62d747499"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "435267c3230ba1439f50fa32c3ed3993a4123f870681451aa95acdde5d52622e"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "93d496f6c25652cf7cca21aac860641ec337d2d6cf00b32cfb52091a1478ee20"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "66d1b7bc973830475a7bae8a5b823ec42fbc1ed1f4d4c514f1e6a21b20177810"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "cf9ae5744c15746a004a660dcdb120e8b81a70b56e3d55ce4d1781d494a2fc58"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "1b4f637283c0c4e87d642641338dee78b0357b97fbc62fe69911cee8d0b557dc"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5553f08402ff3f277f68bf132463f187d14e2b12275ae319f934e4672f4b9288"
metafile = true

[[files]]
file = "mods/no-telemetry.pw.toml"
hash = "8de8d0ef6c5c087ee7c7c028928edcef86527e84a927cef5defb4a7219bf21c5"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "c2ad3d7ad9cad74d92f0d07dc156da21636cd54bd23de7c22529ec27c297d821"
metafile = true

[[files]]
file = "mods/noxesium.pw.toml"
hash = "e4eebf3987a2763598daf549a2b8c80aea1185b3399e5e99b6919d4ca09c8a5d"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "9a0ab52020c3a2d073e71f07ce11b9d2d8ae0a17b8a3cf0c9227029a51df51c3"
metafile = true

[[files]]
file = "mods/particular.pw.toml"
hash = "63a2011c75cdaf07c0a537c1f5c0661b7e5e0471c81625273634f88fed05b9c4"
metafile = true

[[files]]
file = "mods/railoptimization.pw.toml"
hash = "f0e4fa08462afb33daba514f65ac5e96994c84d6a18f6327ee929407c4dd982c"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "c7a632600334f8643c3dca388a7e6b6b30f15607d21dd7cb1bad3f59a52f0f84"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "8b1f5a4ddb33a561b5f7c8067c90da759bee5919e99275587a5d1799fe461064"
metafile = true

[[files]]
file = "mods/scoreboard-overhaul.pw.toml"
hash = "51288d8deb5c7f5c5f249b2f9da7603347c799adff2e01029a5c2c1a95ec962d"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "98739e44d0a6e97c0776861a551cf689d9190a215640210007dd28d3edad9107"
metafile = true

[[files]]
file = "mods/smooth-scroll.pw.toml"
hash = "f985288dc5af3c5fde96f303509839f1836c2a9716c321eb7910b90563413aa3"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "7e247fc51fae1fdaf7cca7a94f7222341d6673b68941a933adafaa4b921ec2b2"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "356a264757b1b5d0eda01c8c09ec7dd40062e93003d1e5ee027d3215eef2e0ce"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "c9707be9953f87c752fc750bc7f54d6d1c10d74e53b7a86fb55357c977c4fd1b"
metafile = true

[[files]]
file = "mods/sushi-bar.pw.toml"
hash = "6bfb09a5bf731cd8d347b8e77b0379c254b2e2dd2763c8051b6bfe122a22b7fb"
metafile = true

[[files]]
file = "mods/toggle-sprint-display.pw.toml"
hash = "e5b27816a403179f62c81fd2c66d0e2fa9312572a7c0e12da40717aac38e6140"
metafile = true

[[files]]
file = "mods/toggle-toggle-sprint.pw.toml"
hash = "3d0e8828e8f96c8c29820aeecb0eb77f3509d23f10fed61adaf658f041829691"
metafile = true

[[files]]
file = "mods/tooltip-scroll.pw.toml"
hash = "59bdc52707f486b9fe875b1896490afd643f2c7931063218272071037c085f74"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "eac5d5405a7020336980c31c15aab41e0a8fd6881f53deca8ad07c247e968206"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "bbbcf529b4c35f04e733922ca06dde4aac8d97a556e4396da25d99e2d079c0c9"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "62ba6e83a70f7fae1d703cf3c1b73a64b07af0ff9bf9b19024ddcd787aca6bad"
metafile = true

[[files]]
file = "resourcepacks/Bolt Resourcepack.zip"
hash = "0036735c57f7734d13042a1eedfcb1ece212d23cc7eda566b9c231ed40266693"

[[files]]
file = "resourcepacks/sleek-ui.pw.toml"
hash = "a9369e0278868a182da5039e663f1a23176df1e4b2a14f38e1621dba66fedb4f"
metafile = true

[[files]]
file = "shaderpacks/miniature-shader.pw.toml"
hash = "8ce5793226da3a42adaf0b6de42a917e47d9da31d6227fd53a06033dbbe47911"
metafile = true
