hash-format = "sha256"

[[files]]
file = "LICENSE"
hash = "002c2696d92b5c8cf956c11072baa58eaf9f6ade995c031ea635c6a1ee342ad1"

[[files]]
file = "config/customwindowtitle-client.toml"
hash = "b2150b19deb5ea3d6088e1492a723639c6c59840c454268530ba8a14a4f9a81f"

[[files]]
file = "config/early-loading-bar.json"
hash = "d8c9a754548bce9fb857619152bf3e68d92944f9190e8a9d529a2a048841ae21"

[[files]]
file = "config/yosbr/config/crosshairaddons.json"
hash = "b75736290ef479d26ca52d0e4298d803c01b4050dd090a843a1188d688b2504b"

[[files]]
file = "config/yosbr/config/cull-less-leaves.json"
hash = "edbe4c405e6f4d1afc642ac979b3dc4453abfc6834506f7be9627458670e23d7"

[[files]]
file = "config/yosbr/config/emotecraft.json"
hash = "503e9e4c16523f50e40e35784e92e2aab2a026d0422a63dd2739b93ef7f3716c"

[[files]]
file = "config/yosbr/config/figura.json"
hash = "96d93b202c2f6875b93ca6aaf73481e2c6ccd2b5fda29a31f446ca3b6ff238f9"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3da48a1e456c64065654658d6b0bc21b78ecaea0d6f469e4d96d840011fd7f50"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "d2e72b5f7489638cf59c5b10b0be9688e7e6ce0dfe6c3e02d68c2ce41ab0d19d"

[[files]]
file = "config/yosbr/config/notenoughanimations.json"
hash = "ed7dfd2c0db1072caab00c05ed29b4e1d8075d2ce686eaa022a283c397940cbc"

[[files]]
file = "config/yosbr/config/replaymod.json"
hash = "07dbafbbac4ebb2bd0a4de319ea2416f9d443f68229a1b45e595abbf902a943b"

[[files]]
file = "config/yosbr/config/scoreboard-overhaul.json"
hash = "aac4f2225b8dec031d07acb5c2a7dda26b5df8b594db7231bbada81454fdc585"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "2445c054393ab40304c9fde7008b404323cd7302e0411d4b4aa32de5f362701e"

[[files]]
file = "config/yosbr/config/zoomify.json"
hash = "839f3e7347c514b0fb4b02fb86fd263943dea9d7a1e60e70fdb3011abf0a944a"

[[files]]
file = "config/yosbr/options.txt"
hash = "6a7314c3a9edd00394c5f6609307c9a9fc14285b33d3589c8a84ffc73a57daf7"

[[files]]
file = "config/yosbr/servers.dat"
hash = "2fb0c8230eaa5ce3b7a67df7177d491937dbce366aea65584753b22aca30c8da"

[[files]]
file = "mods/amecs.pw.toml"
hash = "1e5b00de09f3382cb89564dca455b0d547855c09d8d28d2e98e47d95fabcaeff"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "7d44149b8b22e0b19b082f49809edfc1b5f170e5d1d297cd73ae88c0b432c3ab"
metafile = true

[[files]]
file = "mods/better-clouds.pw.toml"
hash = "bbc29250b58d89e67bfbcbe61c2d5725becfe2486b57d6a1f2114311958ef49c"
metafile = true

[[files]]
file = "mods/better-highlighting.pw.toml"
hash = "b5ef3d63813d67a02294a68ea582a29a3cee95c3bee68966abedb37d82d014d0"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "333dfa2b93c688ce5f9f685f77cb62e5df8b9c8d21a2c4dd4eb9232aa85dccff"
metafile = true

[[files]]
file = "mods/better-suggestions.pw.toml"
hash = "aecd53124823a53eacaee6a3e5194e562d9bd81702c8275b9d814099a84bb5e6"
metafile = true

[[files]]
file = "mods/clean-f3.pw.toml"
hash = "b5af3194d6df56cc66492a178625a37947027a7d761eb29153f33869508a6863"
metafile = true

[[files]]
file = "mods/clientsidenoteblocks.pw.toml"
hash = "614da319097ce96717cd56c3ff3313b8204fc13625d0f70bff27b605725a751e"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/collision-fix.pw.toml"
hash = "7f6f281e6a5666d90cc87624242223735a5942797ae77bfa8bebd098322923ce"
metafile = true

[[files]]
file = "mods/colorful-subtitles.pw.toml"
hash = "356f34e405da834bf9b11375bad6f1de6878daddbddd3cb9e3e799bdafc8c148"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "ca80c5f6b0faca95bbc06192a3da36446ff396b5e6e0304f6779269b60bbdd9d"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "af83eb1ea0f7a36e4424248c744c1cbebb5045d361e843b873d4d89bf65ad8ad"
metafile = true

[[files]]
file = "mods/crosshair-addons-public.pw.toml"
hash = "8676a3f9975536a6fc2ddcb812138cb1e0ce78e5d2321124f25892d877063c4d"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "5944ed5a779d142aea9ccd8c466a20fa3d9233a29f2be1e5ae54fc15f5edd57e"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "e4a437ed5c3f631fd4787e6ad4d61295654aba9d07528a5b692b8e917221ea0d"
metafile = true

[[files]]
file = "mods/custom-window-title.pw.toml"
hash = "54cb969b7cfdde6077ea24d46130186098483b7520dbe4219255f2efb9735931"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "ce0b6c452313b669ce95d6bc7f232f72b89bf61ebb2013cac5b17a09c8132510"
metafile = true

[[files]]
file = "mods/early-loading-bar.pw.toml"
hash = "26ae037d9762efc9fc77183b2083869165fc6d98de006af2f0eb7d156c967e75"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "c9102ad224c1496927d326707ee2cd2a2cfd6f278f05e23a19aa45395306daf6"
metafile = true

[[files]]
file = "mods/effecttimerplus.pw.toml"
hash = "1fd492cd1c570fd7fd953f4bcc27ae204b4107e1d21a54efc9c7d512cc1b5141"
metafile = true

[[files]]
file = "mods/emotecraft.pw.toml"
hash = "bd53dcb193060715c659e96aedafd08dedd193ebb1f0a79fe15f6786a315a6c0"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "58a487d9e3761d18f529cf141c873ea054e8f26c5e90601a3c8cf60fc723b22d"
metafile = true

[[files]]
file = "mods/f3sconfirm.pw.toml"
hash = "edd246bb7ccb7b5cbe21ee578e2a3b276401fcb80d30de78e9c258c42b6bc14f"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "2b7949e506ba69c57139127c0ccc6caf5a9ec5ec97788b81288118db3d7c2ad3"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fadeless.pw.toml"
hash = "d987a241a56c9e3fde315ca942c8240911b51c98d7d5bd1f089c25ddb8b6cca1"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "29d41095d30271247f296402d3e50d8ce060acf77808efcbe25de0ec84e76975"
metafile = true

[[files]]
file = "mods/faster-random.pw.toml"
hash = "605fe60f2ada4333e88ec2fa66cb57d0635292d83eee8d1ad40f2485d72ef013"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "86cbfa8adbbb8be527f95aca49b427f892aa780773df141dfd7f4ffd02740bbd"
metafile = true

[[files]]
file = "mods/figura-badge-backport-tool.pw.toml"
hash = "9c18abf555d41cc36964e2cc22aa8f6ed038b783421ae18911df9fb39e10772a"
metafile = true

[[files]]
file = "mods/figura.pw.toml"
hash = "fcfd264784dcda039d9efc0b3e47ef1f04521698761a34d2f20379d5f9c0fe26"
metafile = true

[[files]]
file = "mods/highlight.pw.toml"
hash = "58ace6ddc01192bd96668e2a833568083f34b0808645e056c0f1e0716f63abe5"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "cb85864ff2d3936a5ab4f7e7ccf763dbda0153412ba52c95a63b29677a012aaf"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "99efc9e805ce2888680d3cacb9be65733c6d4a8cfcb77e1976205f758db24346"
metafile = true

[[files]]
file = "mods/itemphysic-lite.pw.toml"
hash = "4a2a3f5a7bb617eba9acbf39417aaa75433379fb3bcf1a7054b3dbe8bc1bb472"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "9063bac3fdf585a43d318e3f9773475a28ecb8fe80bc7689cc480851eef97420"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "8508e46b7e272d79dc6b3cc0149f9fd132c701369bcb2abb5c35da3ed92b27fb"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c8695e51366b601c5e9118a5d5650d234cc25fc8d1f90ebd186c17c199ba7fca"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ede2f61d6b592f44294fa8790c2f050729c487aa86aba09034f2ef30d45e0e93"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "4b1b29ebfbbd9f23eb90c8c9f5113fce64c3ca605c8cad3aedaa25be83a82a53"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "435267c3230ba1439f50fa32c3ed3993a4123f870681451aa95acdde5d52622e"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "f43c82e3cc6079291ddae81445c703905b6c670dd43f444e47f5cd817944e822"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d7145fd1bd8b4bb6a3b84652a96a68870fb3ab32230f27520bb9362fd17ec39f"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "3dc86c0b4d31199f6f8579b8460686201ce8b9c87e1be5afaf50be9995add1e0"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "b6685e98fce8f1f45868b9df3dbaa410ec23bb64896c826be596d98b01326116"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "9ce6efc7149cdae2deb751b4ebf2d220700cc1b204e7a1d026275203387f106b"
metafile = true

[[files]]
file = "mods/no-telemetry.pw.toml"
hash = "ebd48452773a4b6b4b7dcedbfb71c8986ec97780fcce040542c8e8fd67f22c56"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "89ed99a0798a5e1300434359762c968536593279493f68b321a565fb1343f75c"
metafile = true

[[files]]
file = "mods/noxesium.pw.toml"
hash = "e4eebf3987a2763598daf549a2b8c80aea1185b3399e5e99b6919d4ca09c8a5d"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "df4c4fe3aff1792aa7d19d097d5d1bc0c6e958e6e4ee32dbf148ecac62e1274d"
metafile = true

[[files]]
file = "mods/particular.pw.toml"
hash = "63a2011c75cdaf07c0a537c1f5c0661b7e5e0471c81625273634f88fed05b9c4"
metafile = true

[[files]]
file = "mods/railoptimization.pw.toml"
hash = "f0e4fa08462afb33daba514f65ac5e96994c84d6a18f6327ee929407c4dd982c"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "4a7d1e46795d2d83b18db85d8dbc63740a1d337e12d2b9e550378de59f2b23ab"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "8b1f5a4ddb33a561b5f7c8067c90da759bee5919e99275587a5d1799fe461064"
metafile = true

[[files]]
file = "mods/scoreboard-overhaul.pw.toml"
hash = "51288d8deb5c7f5c5f249b2f9da7603347c799adff2e01029a5c2c1a95ec962d"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "830270b8e5a34f5621720ae09c4cf716a65d8003a30d585c8b817aba1fde9ac8"
metafile = true

[[files]]
file = "mods/smooth-scroll.pw.toml"
hash = "f985288dc5af3c5fde96f303509839f1836c2a9716c321eb7910b90563413aa3"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "8ad07191dfdea31249b4416a390c1cdf1d4ff1938cf9f8a617f98f7a08c5356c"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ecf8e1df2361e5f1d090f83eee16c449ff1021dfb2da46474a72726406d5d535"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "98553c2d49ef3a888954f24b7c49fe3442c01fd4fc1f1ed52c5898ed29d29d3b"
metafile = true

[[files]]
file = "mods/sushi-bar.pw.toml"
hash = "6bfb09a5bf731cd8d347b8e77b0379c254b2e2dd2763c8051b6bfe122a22b7fb"
metafile = true

[[files]]
file = "mods/toggle-sprint-display.pw.toml"
hash = "e5b27816a403179f62c81fd2c66d0e2fa9312572a7c0e12da40717aac38e6140"
metafile = true

[[files]]
file = "mods/toggle-toggle-sprint.pw.toml"
hash = "3d0e8828e8f96c8c29820aeecb0eb77f3509d23f10fed61adaf658f041829691"
metafile = true

[[files]]
file = "mods/tooltip-scroll.pw.toml"
hash = "59bdc52707f486b9fe875b1896490afd643f2c7931063218272071037c085f74"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "8305bf17272f0c579b0930b751c12089de9fb157dbdb5c080836ce3daad310b5"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "d2d5a9c835661b4f6f718fd057f03594b87aa49d1bcd9711af8553e51ea4a6fb"
metafile = true

[[files]]
file = "resourcepacks/Bolt Resourcepack.zip"
hash = "8cd332c0f2cf01969ecb01ea83bfde90cb479d6c9d688bc7de6e9ba0e6cced6c"

[[files]]
file = "resourcepacks/sleek-ui.pw.toml"
hash = "8cde0f16db9e86dfd9a47cb7afc4ebc0081f38588ac121711f4d0cb9905b24dd"
metafile = true

[[files]]
file = "shaderpacks/miniature-shader.pw.toml"
hash = "8ce5793226da3a42adaf0b6de42a917e47d9da31d6227fd53a06033dbbe47911"
metafile = true
