name = "Snowy's Bolt Pack"
author = "Snowy893"
version = "v1.0.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3af5beec4504e53b955e832164a80ab11b1d62dea60dde063007351a2692981"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
