name = "Snowy's Bolt Pack"
author = "Snowy893"
version = "v1.1.2+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94bcb2994895fae4647c8f08b4a3c56776afb35e69c4bb66d72bc5eed6d23607"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
