name = "Snowy's Bolt Pack"
author = "Snowy893"
version = "v1.0.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "520cf6b458afa28235e51f531a3461df394fc8637f522fb6dbef525d962c5857"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
