name = "Snowy's Bolt Pack"
author = "Snowy893"
version = "v1.0.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d91adf7cd9887e4391b78b647a33f60cd13f79c64da636a116397b91c3b6392a"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
