name = "Snowy's Bolt Pack"
author = "Snowy893"
version = "v1.3.1+1.20.1"
description = "For playing the one-shot bow minigame!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e4b96cdfbe9d75469be067c801279180f16e690bb6ad85772c3bc257e9e3c1a"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
